SampleScratch3/force-app/main/default/objects/CusManage__c/CusManage__c.object-meta.xml
<CustomObject>
    <label>顧客管理</label>
    <nameField>
        <label>顧客名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SampleScratch3/force-app/main/default/objects/CusManage__c/fields/sign__c.field-meta.xml
<CustomField>
    <fullName>sign__c</fullName>
    <label>サイン</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SampleScratch4/force-app/main/default/objects/CusManage__c/recordTypes/CusManage.recordType-meta.xml
<RecordType>
    <fullName>CusManage</fullName>
    <active>true</active>
    <label>顧客管理</label>
</RecordType>

SampleScratch4/force-app/main/default/classes/CusManageWrapper.cls
public class CusManageWrapper {
    public CusManage__c cmRecord {get; set;}
    public List<String> signUrlList {get; set;}
    
    public CusManageWrapper() {}
    
    public CusManageWrapper(CusManage__c cusManage) {
        this.cmRecord = cusManage;
        
        //サイン画像のURLをリストに格納
        String strFirst = 'img src=\"';
        String strLast = '\"';
        Integer startNum = 0;
        Integer lastNum = 0;
        String tmpWd = cusManage.sign__c;
        signUrlList = new List<String>();
        
        while(String.isNotEmpty(tmpWd) && tmpWd.indexOf(strFirst) > 0) {
            startNum = tmpWd.indexOf(strFirst) + strFirst.length();
            lastNum = tmpWd.indexOf(strLast, startNum);
            signUrlList.add(tmpWd.substring(startNum, lastNum));
            tmpWd = tmpWd.substring(lastNum);
        }
        
        //System.debug('顧客名 : ' + cusManage.Name + ' サイン画像URL : ' + signUrlList);
    }
}